### ISSUE TITLE
Typescript 1.7+ support

### ISSUE THREAD

**Issue by RomanKisilenko** [TypeStrong/tsify#104]
Attempt to transpile code using latest angular 2 fails since it expects Typescript 1.7 to be used. 

Please consider updating tsify to Typescript 1.7.

**Comment by blakeembrey** [comment]
It should work with TypeScript 1.7 already, unless I'm mistaken. What error are you getting? What version are you using?

**Comment by RomanKisilenko** [comment]
Hi, indeed, we were using 0.12.2 version which support Typescript 1.6 only. I upgraded to 0.13.1 and now typescript compiler is not able to locate typings in npm modules anymore. While there is an npm module named angular2 in node_modules and corresponding typing in a module, I'm getting errors like
```TypeScript error: src/index.ts(8,25): Error TS2307: Cannot find module 'angular2/angular2'```
Is there any way to force the typescript compiler to look for typings in npm modules like it was doing for  0.12.2 version?

**Comment by RomanKisilenko** [comment]
Never mind, it is due to angular2 constantly changing. Sorry for false bug report.
