### ISSUE TITLE
Object.assign is not a function

### ISSUE THREAD

**Issue by APLmath** [TypeStrong/tsify#198]
Recently, I npm installed gulp and tsify (among other things), but when I run a gulp task that uses tsify, it fails with an "undefined is not a function". Here's a snippet of the output:

    TypeError: undefined is not a function
    at parseOptions (.../node_modules/tsify/lib/Tsifier.js:59:17)
    at new Tsifier (.../node_modules/tsify/lib/Tsifier.js:127:23)
    at tsify (.../node_modules/tsify/index.js:19:16)
    at Browserify.plugin (.../node_modules/browserify/index.js:353:9)
    at Gulp.<anonymous> (.../gulpfile.js:21:6)

Looks like it's complaining about `Object.assign`, which according to my web searches, is not built into Node. It was introduced in https://github.com/TypeStrong/tsify/commit/7c9b1af854ec0982ca28335e6c4137129ff35a6d

**Comment by cartant** [comment]
Thanks. I'll patch this soon and will update the Travis configuration so that the tests are also run on the earliest supported version of Node.
