### ISSUE TITLE
Tsify doesn't support enum strings

### ISSUE THREAD

**Issue by sebastien-fragnaud** [TypeStrong/tsify#118]
Hello and thanks for this project !

When transpiling React.d.ts (installed though Typings), I got the following error :
```
TypeScript error: typings/browser/ambient/react/index.d.ts(1008,22): Error TS1110: Type expected.
```

The incriminated line is :
```
backgroundAttachment?: "scroll" | "fixed" | "local";
```

When changing the union type into `any`, the problem goes away.

Any hint ?

**Comment by sebastien-fragnaud** [comment]
I'm a moron. That's caused by Typescript 1.7.5, and in Tsify's master branch, it's already on 1.8.7 or something. I'll just wait for the next release (or is it released already ?).

**Comment by delphinus35** [comment]
You have to use `--typescript` option to compile with your own TS such as TS 1.8.x. But soon it will be updated to use TS 1.8.x in master, I think.
